{{- if .Values.keyVault.enabled }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: orchestrator-kv
spec:
  provider: azure
  parameters:
    clientID: {{ include "orch.clientId" . | quote }}
    keyvaultName: {{ include "orch.keyVaultName" . | quote }}
    tenantId: {{ include "orch.tenantId" . | quote }}
    objects: |
      array:
{{- range $kv, $env := .Values.keyVault.secrets }}
        - |
          objectName: {{ $kv }}
          objectType: secret
{{- end }}
  secretObjects:
    - secretName: orchestrator-secrets
      type: Opaque
      data:
{{- range $kv, $env := .Values.keyVault.secrets }}
        - {objectName: {{ $kv }}, key: {{ $kv }}}
{{- end }}
{{- end }}
