apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
  labels: {{- include "orch.labels" . | nindent 4 }}
  annotations:
    azure.workload.identity/client-id: {{ include "orch.clientId" . | quote }}
