// Azure test environment for the agent orchestrator (resource group scope).
//
//   AKS (Azure CNI overlay + Cilium network policy, Workload Identity, Key Vault CSI,
//   application routing), ACR, Key Vault, PostgreSQL Flexible Server (private),
//   Azure Managed Redis (private endpoint), Azure AI Speech, Log Analytics +
//   Application Insights, a LiveKit server VM with automatic TLS, and one
//   user-assigned managed identity per workload with its federated credential.
//
// Deployed by deploy/azure/deploy.sh, which generates the secrets passed here and
// keeps them stable across runs. See docs/AZURE_TEST_ENV.md.

@description('Short lowercase prefix for resource names, e.g. aotest.')
@minLength(3)
@maxLength(12)
param prefix string

param location string = resourceGroup().location

@description('DNS label of the public ingress: <label>.<region>.cloudapp.azure.com (test client, token service, console).')
param appDnsLabel string

@description('DNS label of the LiveKit server VM.')
param livekitDnsLabel string

@description('Object id of the person or pipeline running the deployment (Key Vault Secrets Officer).')
param deployerPrincipalId string

@allowed(['User', 'ServicePrincipal'])
param deployerPrincipalType string = 'User'

param livekitAdminUser string = 'livekit'

@description('SSH public key for the LiveKit VM admin user.')
param livekitSshPublicKey string

@description('Source range allowed to SSH to the LiveKit VM; empty disables SSH from the internet.')
param sshSourceCidr string = ''

param aksNodeSize string = 'Standard_D4s_v5'
param aksNodeMin int = 2
param aksNodeMax int = 4
param livekitVmSize string = 'Standard_D2s_v5'

@description('Email for the LiveKit VM Let\'s Encrypt account (optional).')
param acmeEmail string = ''

// Secrets generated by deploy.sh (stable across runs).
@secure()
param pgAdminPassword string
@secure()
param sessionKey string
@secure()
param approvalKey string
@secure()
param dispatchKey string
@secure()
param temporalPayloadKey string
@secure()
param livekitApiKey string
@secure()
param livekitApiSecret string
@secure()
param consoleCookieSecret string

var suffix = uniqueString(resourceGroup().id)
var names = {
  law: 'log-${prefix}'
  appi: 'appi-${prefix}'
  vnet: 'vnet-${prefix}'
  aks: 'aks-${prefix}'
  acr: 'acr${prefix}${take(suffix, 6)}'
  kv: 'kv-${prefix}-${take(suffix, 6)}'
  pg: 'pg-${prefix}-${take(suffix, 6)}'
  redis: 'redis-${prefix}-${take(suffix, 6)}'
  speech: 'speech-${prefix}-${take(suffix, 6)}'
  livekit: 'vm-${prefix}-livekit'
}
// Address plan: keep in sync with deploy/azure/values/*.yaml (NetworkPolicy egress ranges).
var addr = {
  vnet: '10.60.0.0/16'
  aks: '10.60.0.0/22'
  pg: '10.60.8.0/24'
  pe: '10.60.9.0/24'
  livekit: '10.60.10.0/24'
}
// Workloads with their Kubernetes service accounts (namespace/name) and Key Vault access.
var workloads = [
  { key: 'orchestrator', namespace: 'orchestrator', serviceAccount: 'orchestrator', keyVault: true }
  { key: 'tokenService', namespace: 'edge', serviceAccount: 'token-service', keyVault: true }
  { key: 'clientBackend', namespace: 'edge', serviceAccount: 'test-client', keyVault: false }
  { key: 'masterAgent', namespace: 'voice', serviceAccount: 'master-agent', keyVault: true }
  { key: 'consoleProxy', namespace: 'edge', serviceAccount: 'console-proxy', keyVault: true }
]
var roles = {
  acrPull: '7f951dda-4ed3-4680-a7ca-43fe172d538d'
  kvSecretsUser: '4633458b-17de-408a-b874-0445c86b69e6'
  kvSecretsOfficer: 'b86a8fe4-44ce-4948-aee5-eccb2c155cd7'
  networkContributor: '4d97b98b-1d4f-4787-a291-c67834d212e7'
}

// ------------------------------------------------------------------ monitoring

resource law 'Microsoft.OperationalInsights/workspaces@2023-09-01' = {
  name: names.law
  location: location
  properties: {
    sku: { name: 'PerGB2018' }
    retentionInDays: 30
  }
}

resource appi 'Microsoft.Insights/components@2020-02-02' = {
  name: names.appi
  location: location
  kind: 'web'
  properties: {
    Application_Type: 'web'
    WorkspaceResourceId: law.id
  }
}

// ------------------------------------------------------------------ network

resource livekitNsg 'Microsoft.Network/networkSecurityGroups@2024-05-01' = {
  name: 'nsg-${prefix}-livekit'
  location: location
  properties: {
    securityRules: concat([
      {
        name: 'https-and-acme'
        properties: {
          priority: 100, direction: 'Inbound', access: 'Allow', protocol: 'Tcp'
          sourceAddressPrefix: 'Internet', sourcePortRange: '*', destinationAddressPrefix: '*'
          destinationPortRanges: ['80', '443']
        }
      }
      {
        name: 'webrtc-tcp'
        properties: {
          priority: 110, direction: 'Inbound', access: 'Allow', protocol: 'Tcp'
          sourceAddressPrefix: '*', sourcePortRange: '*', destinationAddressPrefix: '*', destinationPortRange: '7881'
        }
      }
      {
        name: 'webrtc-udp'
        properties: {
          priority: 120, direction: 'Inbound', access: 'Allow', protocol: 'Udp'
          sourceAddressPrefix: '*', sourcePortRange: '*', destinationAddressPrefix: '*', destinationPortRange: '50000-60000'
        }
      }
    ], empty(sshSourceCidr) ? [] : [
      {
        name: 'ssh-admin'
        properties: {
          priority: 200, direction: 'Inbound', access: 'Allow', protocol: 'Tcp'
          sourceAddressPrefix: sshSourceCidr, sourcePortRange: '*', destinationAddressPrefix: '*', destinationPortRange: '22'
        }
      }
    ])
  }
}

resource vnet 'Microsoft.Network/virtualNetworks@2024-05-01' = {
  name: names.vnet
  location: location
  properties: {
    addressSpace: { addressPrefixes: [addr.vnet] }
    subnets: [
      { name: 'snet-aks', properties: { addressPrefix: addr.aks } }
      {
        name: 'snet-pg'
        properties: {
          addressPrefix: addr.pg
          delegations: [{ name: 'pg', properties: { serviceName: 'Microsoft.DBforPostgreSQL/flexibleServers' } }]
        }
      }
      { name: 'snet-pe', properties: { addressPrefix: addr.pe } }
      { name: 'snet-livekit', properties: { addressPrefix: addr.livekit, networkSecurityGroup: { id: livekitNsg.id } } }
    ]
  }
}

resource aksSubnet 'Microsoft.Network/virtualNetworks/subnets@2024-05-01' existing = {
  parent: vnet
  name: 'snet-aks'
}
resource pgSubnet 'Microsoft.Network/virtualNetworks/subnets@2024-05-01' existing = {
  parent: vnet
  name: 'snet-pg'
}
resource peSubnet 'Microsoft.Network/virtualNetworks/subnets@2024-05-01' existing = {
  parent: vnet
  name: 'snet-pe'
}
resource livekitSubnet 'Microsoft.Network/virtualNetworks/subnets@2024-05-01' existing = {
  parent: vnet
  name: 'snet-livekit'
}

// ------------------------------------------------------------------ registry and cluster

resource acr 'Microsoft.ContainerRegistry/registries@2023-07-01' = {
  name: names.acr
  location: location
  sku: { name: 'Basic' }
  properties: { adminUserEnabled: false }
}

resource aks 'Microsoft.ContainerService/managedClusters@2025-05-01' = {
  name: names.aks
  location: location
  identity: { type: 'SystemAssigned' }
  sku: { name: 'Base', tier: 'Free' }
  properties: {
    dnsPrefix: '${prefix}-aks'
    agentPoolProfiles: [
      {
        name: 'system'
        mode: 'System'
        vmSize: aksNodeSize
        osType: 'Linux'
        osSKU: 'AzureLinux'
        type: 'VirtualMachineScaleSets'
        enableAutoScaling: true
        count: aksNodeMin
        minCount: aksNodeMin
        maxCount: aksNodeMax
        vnetSubnetID: aksSubnet.id
        availabilityZones: ['1', '2', '3']
      }
    ]
    networkProfile: {
      networkPlugin: 'azure'
      networkPluginMode: 'overlay'
      networkDataplane: 'cilium'
      networkPolicy: 'cilium'
      podCidr: '192.168.0.0/16'
      serviceCidr: '10.0.0.0/16'
      dnsServiceIP: '10.0.0.10'
      loadBalancerSku: 'standard'
      outboundType: 'loadBalancer'
    }
    oidcIssuerProfile: { enabled: true }
    securityProfile: { workloadIdentity: { enabled: true } }
    ingressProfile: { webAppRouting: { enabled: true } }
    addonProfiles: {
      azureKeyvaultSecretsProvider: {
        enabled: true
        config: { enableSecretRotation: 'true', rotationPollInterval: '2m' }
      }
      omsagent: {
        enabled: true
        config: { logAnalyticsWorkspaceResourceID: law.id }
      }
    }
    autoUpgradeProfile: { upgradeChannel: 'patch', nodeOSUpgradeChannel: 'NodeImage' }
  }
}

resource aksNetwork 'Microsoft.Authorization/roleAssignments@2022-04-01' = {
  name: guid(aksSubnet.id, aks.id, roles.networkContributor)
  scope: aksSubnet
  properties: {
    principalId: aks.identity.principalId
    principalType: 'ServicePrincipal'
    roleDefinitionId: subscriptionResourceId('Microsoft.Authorization/roleDefinitions', roles.networkContributor)
  }
}

resource acrPull 'Microsoft.Authorization/roleAssignments@2022-04-01' = {
  name: guid(acr.id, aks.id, roles.acrPull)
  scope: acr
  properties: {
    principalId: aks.properties.identityProfile.kubeletidentity.objectId
    principalType: 'ServicePrincipal'
    roleDefinitionId: subscriptionResourceId('Microsoft.Authorization/roleDefinitions', roles.acrPull)
  }
}

// ------------------------------------------------------------------ workload identities

resource identities 'Microsoft.ManagedIdentity/userAssignedIdentities@2023-01-31' = [for w in workloads: {
  name: 'id-${prefix}-${toLower(w.key)}'
  location: location
}]

resource federations 'Microsoft.ManagedIdentity/userAssignedIdentities/federatedIdentityCredentials@2023-01-31' = [for (w, i) in workloads: {
  parent: identities[i]
  name: 'aks-${w.namespace}-${w.serviceAccount}'
  properties: {
    issuer: aks.properties.oidcIssuerProfile.issuerURL
    subject: 'system:serviceaccount:${w.namespace}:${w.serviceAccount}'
    audiences: ['api://AzureADTokenExchange']
  }
}]

// ------------------------------------------------------------------ Key Vault

resource kv 'Microsoft.KeyVault/vaults@2023-07-01' = {
  name: names.kv
  location: location
  properties: {
    tenantId: subscription().tenantId
    sku: { family: 'A', name: 'standard' }
    enableRbacAuthorization: true
    enableSoftDelete: true
    softDeleteRetentionInDays: 7
    publicNetworkAccess: 'Enabled'
  }
}

resource kvWorkloads 'Microsoft.Authorization/roleAssignments@2022-04-01' = [for (w, i) in workloads: if (w.keyVault) {
  name: guid(kv.id, w.key, roles.kvSecretsUser)
  scope: kv
  properties: {
    principalId: identities[i].properties.principalId
    principalType: 'ServicePrincipal'
    roleDefinitionId: subscriptionResourceId('Microsoft.Authorization/roleDefinitions', roles.kvSecretsUser)
  }
}]

resource kvDeployer 'Microsoft.Authorization/roleAssignments@2022-04-01' = {
  name: guid(kv.id, deployerPrincipalId, roles.kvSecretsOfficer)
  scope: kv
  properties: {
    principalId: deployerPrincipalId
    principalType: deployerPrincipalType
    roleDefinitionId: subscriptionResourceId('Microsoft.Authorization/roleDefinitions', roles.kvSecretsOfficer)
  }
}

// ------------------------------------------------------------------ PostgreSQL (audit ledger)

resource pgDns 'Microsoft.Network/privateDnsZones@2024-06-01' = {
  name: '${prefix}.private.postgres.database.azure.com'
  location: 'global'
}

resource pgDnsLink 'Microsoft.Network/privateDnsZones/virtualNetworkLinks@2024-06-01' = {
  parent: pgDns
  name: 'vnet'
  location: 'global'
  properties: {
    virtualNetwork: { id: vnet.id }
    registrationEnabled: false
  }
}

resource pg 'Microsoft.DBforPostgreSQL/flexibleServers@2024-08-01' = {
  name: names.pg
  location: location
  sku: { name: 'Standard_B1ms', tier: 'Burstable' }
  properties: {
    version: '16'
    administratorLogin: 'orchadmin'
    administratorLoginPassword: pgAdminPassword
    storage: { storageSizeGB: 32 }
    backup: { backupRetentionDays: 7, geoRedundantBackup: 'Disabled' }
    highAvailability: { mode: 'Disabled' }
    network: {
      delegatedSubnetResourceId: pgSubnet.id
      privateDnsZoneArmResourceId: pgDns.id
      publicNetworkAccess: 'Disabled'
    }
    authConfig: { passwordAuth: 'Enabled', activeDirectoryAuth: 'Disabled' }
  }
  dependsOn: [pgDnsLink]
}

resource pgDb 'Microsoft.DBforPostgreSQL/flexibleServers/databases@2024-08-01' = {
  parent: pg
  name: 'orch'
  properties: { charset: 'UTF8', collation: 'en_US.utf8' }
}

// ------------------------------------------------------------------ Azure Managed Redis (sessions, locks, event bus, admission)

resource redis 'Microsoft.Cache/redisEnterprise@2025-04-01' = {
  name: names.redis
  location: location
  sku: { name: 'Balanced_B0' }
  properties: {
    minimumTlsVersion: '1.2'
    highAvailability: 'Disabled'
  }
}

resource redisDb 'Microsoft.Cache/redisEnterprise/databases@2025-04-01' = {
  parent: redis
  name: 'default'
  properties: {
    clientProtocol: 'Encrypted'
    port: 10000
    clusteringPolicy: 'EnterpriseCluster'
    evictionPolicy: 'NoEviction'
    accessKeysAuthentication: 'Enabled'
  }
}

resource redisDns 'Microsoft.Network/privateDnsZones@2024-06-01' = {
  name: 'privatelink.redis.azure.net'
  location: 'global'
}

resource redisDnsLink 'Microsoft.Network/privateDnsZones/virtualNetworkLinks@2024-06-01' = {
  parent: redisDns
  name: 'vnet'
  location: 'global'
  properties: {
    virtualNetwork: { id: vnet.id }
    registrationEnabled: false
  }
}

resource redisPe 'Microsoft.Network/privateEndpoints@2024-05-01' = {
  name: 'pe-${names.redis}'
  location: location
  properties: {
    subnet: { id: peSubnet.id }
    privateLinkServiceConnections: [
      { name: 'redis', properties: { privateLinkServiceId: redis.id, groupIds: ['redisEnterprise'] } }
    ]
  }
}

resource redisPeDns 'Microsoft.Network/privateEndpoints/privateDnsZoneGroups@2024-05-01' = {
  parent: redisPe
  name: 'default'
  properties: {
    privateDnsZoneConfigs: [{ name: 'redis', properties: { privateDnsZoneId: redisDns.id } }]
  }
}

// ------------------------------------------------------------------ Azure AI Speech (STT/TTS in Switzerland North)

resource speech 'Microsoft.CognitiveServices/accounts@2024-10-01' = {
  name: names.speech
  location: location
  kind: 'SpeechServices'
  sku: { name: 'S0' }
  properties: {
    customSubDomainName: names.speech
    publicNetworkAccess: 'Enabled'
  }
}

// ------------------------------------------------------------------ secrets

// Generated secrets (deploy-time values).
var generatedSecrets = [
  { name: 'orch-session-key', value: sessionKey }
  { name: 'orch-approval-key', value: approvalKey }
  { name: 'orch-temporal-payload-key', value: temporalPayloadKey }
  { name: 'ma-dispatch-key', value: dispatchKey }
  { name: 'livekit-api-key', value: livekitApiKey }
  { name: 'livekit-api-secret', value: livekitApiSecret }
  { name: 'console-cookie-secret', value: consoleCookieSecret }
  { name: 'pg-admin-password', value: pgAdminPassword }
]

resource generated 'Microsoft.KeyVault/vaults/secrets@2023-07-01' = [for s in generatedSecrets: {
  parent: kv
  name: s.name
  properties: { value: s.value }
}]

// Connection secrets derived from the resources above.
resource auditDsn 'Microsoft.KeyVault/vaults/secrets@2023-07-01' = {
  parent: kv
  name: 'orch-audit-dsn'
  properties: {
    value: 'postgresql://orchadmin:${pgAdminPassword}@${pg.properties.fullyQualifiedDomainName}:5432/${pgDb.name}?sslmode=require'
  }
}

resource redisUrl 'Microsoft.KeyVault/vaults/secrets@2023-07-01' = {
  parent: kv
  name: 'orch-redis-url'
  properties: {
    value: 'rediss://:${uriComponent(redisDb.listKeys().primaryKey)}@${redis.properties.hostName}:10000/0'
  }
}

resource speechKey 'Microsoft.KeyVault/vaults/secrets@2023-07-01' = {
  parent: kv
  name: 'speech-key'
  properties: { value: speech.listKeys().key1 }
}

resource appiConnection 'Microsoft.KeyVault/vaults/secrets@2023-07-01' = {
  parent: kv
  name: 'appinsights-connection-string'
  properties: { value: appi.properties.ConnectionString }
}

// ------------------------------------------------------------------ LiveKit server VM

resource livekitIp 'Microsoft.Network/publicIPAddresses@2024-05-01' = {
  name: 'pip-${names.livekit}'
  location: location
  sku: { name: 'Standard' }
  properties: {
    publicIPAllocationMethod: 'Static'
    dnsSettings: { domainNameLabel: livekitDnsLabel }
  }
}

resource livekitNic 'Microsoft.Network/networkInterfaces@2024-05-01' = {
  name: 'nic-${names.livekit}'
  location: location
  properties: {
    ipConfigurations: [
      {
        name: 'ipconfig'
        properties: {
          subnet: { id: livekitSubnet.id }
          privateIPAllocationMethod: 'Dynamic'
          publicIPAddress: { id: livekitIp.id }
        }
      }
    ]
  }
}

var livekitFqdn = '${livekitDnsLabel}.${location}.cloudapp.azure.com'
var cloudInit = replace(replace(replace(loadTextContent('livekit/cloud-init.yaml'), '__KEY_VAULT__', names.kv), '__LIVEKIT_FQDN__', livekitFqdn), '__ACME_EMAIL__', acmeEmail)

resource livekitVm 'Microsoft.Compute/virtualMachines@2024-07-01' = {
  name: names.livekit
  location: location
  identity: { type: 'SystemAssigned' }
  properties: {
    hardwareProfile: { vmSize: livekitVmSize }
    osProfile: {
      computerName: 'livekit'
      adminUsername: livekitAdminUser
      customData: base64(cloudInit)
      linuxConfiguration: {
        disablePasswordAuthentication: true
        ssh: { publicKeys: [{ path: '/home/${livekitAdminUser}/.ssh/authorized_keys', keyData: livekitSshPublicKey }] }
      }
    }
    storageProfile: {
      imageReference: { publisher: 'Canonical', offer: 'ubuntu-24_04-lts', sku: 'server', version: 'latest' }
      osDisk: { createOption: 'FromImage', managedDisk: { storageAccountType: 'StandardSSD_LRS' }, deleteOption: 'Delete' }
    }
    networkProfile: { networkInterfaces: [{ id: livekitNic.id, properties: { deleteOption: 'Delete' } }] }
    securityProfile: { securityType: 'TrustedLaunch', uefiSettings: { secureBootEnabled: true, vTpmEnabled: true } }
  }
}

// The VM reads the LiveKit keys from Key Vault at boot (retrying until this assignment propagates).
resource kvLivekit 'Microsoft.Authorization/roleAssignments@2022-04-01' = {
  name: guid(kv.id, livekitVm.id, roles.kvSecretsUser)
  scope: kv
  properties: {
    principalId: livekitVm.identity.principalId
    principalType: 'ServicePrincipal'
    roleDefinitionId: subscriptionResourceId('Microsoft.Authorization/roleDefinitions', roles.kvSecretsUser)
  }
}

// ------------------------------------------------------------------ outputs (no secrets)

output aksName string = aks.name
output acrName string = acr.name
output acrLoginServer string = acr.properties.loginServer
output keyVaultName string = kv.name
output oidcIssuer string = aks.properties.oidcIssuerProfile.issuerURL
output tenantId string = subscription().tenantId
output appHost string = '${appDnsLabel}.${location}.cloudapp.azure.com'
output livekitHost string = livekitIp.properties.dnsSettings.fqdn
output speechRegion string = location
output identities array = [for (w, i) in workloads: { key: w.key, clientId: identities[i].properties.clientId }]
