// Azure test environment for the agent orchestrator (resource group scope).
//
//   One Ubuntu VM runs every component with Docker Compose (deploy/azure/vm):
//   Caddy (TLS), LiveKit, the orchestrator and its worker, OPA, Temporal, Redis,
//   PostgreSQL, the OTel collector, the A2A gateway, the domain agents, the fake
//   bank, the token service, the test client, the console sign-in proxy and the
//   master agent. Around it: Key Vault (secrets), ACR (images), Azure AI Speech,
//   Log Analytics + Application Insights, and one user-assigned managed identity
//   per calling workload, all attached to the VM.
//
// Deployed by deploy.sh, which generates the secrets passed here and keeps them
// stable across runs. See docs/AZURE_TEST_ENV.md.

@description('Short lowercase prefix for resource names, e.g. aotest.')
@minLength(3)
@maxLength(12)
param prefix string

param location string = resourceGroup().location

@description('DNS label of the VM: <label>.<region>.cloudapp.azure.com (test client, token service, console, LiveKit).')
param dnsLabel string

@description('Object id of the person or pipeline running the deployment (Key Vault Secrets Officer).')
param deployerPrincipalId string

@allowed(['User', 'ServicePrincipal'])
param deployerPrincipalType string = 'User'

param adminUser string = 'azureuser'

@description('SSH public key for the VM admin user.')
param sshPublicKey string

@description('Source range allowed to SSH to the VM; empty disables SSH from the internet.')
param sshSourceCidr string = ''

@description('VM size; 4 vCPUs and 16 GiB run the whole environment including voice.')
param vmSize string = 'Standard_D4s_v5'

@minValue(64)
param osDiskSizeGB int = 128

// Secrets generated by deploy.sh (stable across runs).
@secure()
param pgPassword string
@secure()
param redisPassword string
@secure()
param sessionKey string
@secure()
param approvalKey string
@secure()
param dispatchKey string
@secure()
param temporalPayloadKey string
@secure()
param livekitApiKey string
@secure()
param livekitApiSecret string
@secure()
param consoleCookieSecret string

var suffix = uniqueString(resourceGroup().id)
var names = {
  law: 'log-${prefix}'
  appi: 'appi-${prefix}'
  acr: 'acr${prefix}${take(suffix, 6)}'
  kv: 'kv-${prefix}-${take(suffix, 6)}'
  speech: 'speech-${prefix}-${take(suffix, 6)}'
  vm: 'vm-${prefix}'
  vnet: 'vnet-${prefix}-vm'
}
// Workloads that call Entra ID with their own managed identity (IMDS on the VM):
// the orchestrator (on-behalf-of, trusted by its app as a federated credential) and
// the callers of the orchestrator API (checked against auth.route_callers).
var workloads = ['orchestrator', 'tokenService', 'clientBackend', 'masterAgent']
var roles = {
  acrPull: '7f951dda-4ed3-4680-a7ca-43fe172d538d'
  kvSecretsUser: '4633458b-17de-408a-b874-0445c86b69e6'
  kvSecretsOfficer: 'b86a8fe4-44ce-4948-aee5-eccb2c155cd7'
}

// ------------------------------------------------------------------ monitoring

resource law 'Microsoft.OperationalInsights/workspaces@2023-09-01' = {
  name: names.law
  location: location
  properties: {
    sku: { name: 'PerGB2018' }
    retentionInDays: 30
  }
}

resource appi 'Microsoft.Insights/components@2020-02-02' = {
  name: names.appi
  location: location
  kind: 'web'
  properties: {
    Application_Type: 'web'
    WorkspaceResourceId: law.id
  }
}

// ------------------------------------------------------------------ registry, speech, identities

resource acr 'Microsoft.ContainerRegistry/registries@2023-07-01' = {
  name: names.acr
  location: location
  sku: { name: 'Basic' }
  properties: { adminUserEnabled: false }
}

resource speech 'Microsoft.CognitiveServices/accounts@2024-10-01' = {
  name: names.speech
  location: location
  kind: 'SpeechServices'
  sku: { name: 'S0' }
  properties: {
    customSubDomainName: names.speech
    publicNetworkAccess: 'Enabled'
  }
}

resource identities 'Microsoft.ManagedIdentity/userAssignedIdentities@2023-01-31' = [for w in workloads: {
  name: 'id-${prefix}-${toLower(w)}'
  location: location
}]

// ------------------------------------------------------------------ Key Vault

resource kv 'Microsoft.KeyVault/vaults@2023-07-01' = {
  name: names.kv
  location: location
  properties: {
    tenantId: subscription().tenantId
    sku: { family: 'A', name: 'standard' }
    enableRbacAuthorization: true
    enableSoftDelete: true
    softDeleteRetentionInDays: 7
    publicNetworkAccess: 'Enabled'
  }
}

resource kvDeployer 'Microsoft.Authorization/roleAssignments@2022-04-01' = {
  name: guid(kv.id, deployerPrincipalId, roles.kvSecretsOfficer)
  scope: kv
  properties: {
    principalId: deployerPrincipalId
    principalType: deployerPrincipalType
    roleDefinitionId: subscriptionResourceId('Microsoft.Authorization/roleDefinitions', roles.kvSecretsOfficer)
  }
}

var generatedSecrets = [
  { name: 'orch-session-key', value: sessionKey }
  { name: 'orch-approval-key', value: approvalKey }
  { name: 'orch-temporal-payload-key', value: temporalPayloadKey }
  { name: 'ma-dispatch-key', value: dispatchKey }
  { name: 'livekit-api-key', value: livekitApiKey }
  { name: 'livekit-api-secret', value: livekitApiSecret }
  { name: 'console-cookie-secret', value: consoleCookieSecret }
  { name: 'pg-admin-password', value: pgPassword }
  { name: 'redis-password', value: redisPassword }
]

resource generated 'Microsoft.KeyVault/vaults/secrets@2023-07-01' = [for s in generatedSecrets: {
  parent: kv
  name: s.name
  properties: { value: s.value }
}]

resource speechKey 'Microsoft.KeyVault/vaults/secrets@2023-07-01' = {
  parent: kv
  name: 'speech-key'
  properties: { value: speech.listKeys().key1 }
}

resource appiConnection 'Microsoft.KeyVault/vaults/secrets@2023-07-01' = {
  parent: kv
  name: 'appinsights-connection-string'
  properties: { value: appi.properties.ConnectionString }
}

// ------------------------------------------------------------------ network

resource nsg 'Microsoft.Network/networkSecurityGroups@2024-05-01' = {
  name: 'nsg-${names.vm}'
  location: location
  properties: {
    // HTTPS stays open to the internet so Let's Encrypt can validate the certificate;
    // ALLOWED_SOURCE_RANGES restricts the application itself (in Caddy).
    securityRules: concat([
      {
        name: 'https-and-acme'
        properties: {
          priority: 100, direction: 'Inbound', access: 'Allow', protocol: 'Tcp'
          sourceAddressPrefix: 'Internet', sourcePortRange: '*', destinationAddressPrefix: '*'
          destinationPortRanges: ['80', '443']
        }
      }
      {
        name: 'webrtc-tcp'
        properties: {
          priority: 110, direction: 'Inbound', access: 'Allow', protocol: 'Tcp'
          sourceAddressPrefix: '*', sourcePortRange: '*', destinationAddressPrefix: '*', destinationPortRange: '7881'
        }
      }
      {
        name: 'webrtc-udp'
        properties: {
          priority: 120, direction: 'Inbound', access: 'Allow', protocol: 'Udp'
          sourceAddressPrefix: '*', sourcePortRange: '*', destinationAddressPrefix: '*', destinationPortRange: '50000-60000'
        }
      }
    ], empty(sshSourceCidr) ? [] : [
      {
        name: 'ssh-admin'
        properties: {
          priority: 200, direction: 'Inbound', access: 'Allow', protocol: 'Tcp'
          sourceAddressPrefix: sshSourceCidr, sourcePortRange: '*', destinationAddressPrefix: '*', destinationPortRange: '22'
        }
      }
    ])
  }
}

resource vnet 'Microsoft.Network/virtualNetworks@2024-05-01' = {
  name: names.vnet
  location: location
  properties: {
    addressSpace: { addressPrefixes: ['10.61.0.0/24'] }
    subnets: [
      { name: 'snet-vm', properties: { addressPrefix: '10.61.0.0/26', networkSecurityGroup: { id: nsg.id } } }
    ]
  }
}

resource pip 'Microsoft.Network/publicIPAddresses@2024-05-01' = {
  name: 'pip-${names.vm}'
  location: location
  sku: { name: 'Standard' }
  properties: {
    publicIPAllocationMethod: 'Static'
    dnsSettings: { domainNameLabel: dnsLabel }
  }
}

resource nic 'Microsoft.Network/networkInterfaces@2024-05-01' = {
  name: 'nic-${names.vm}'
  location: location
  properties: {
    ipConfigurations: [
      {
        name: 'ipconfig'
        properties: {
          subnet: { id: vnet.properties.subnets[0].id }
          privateIPAllocationMethod: 'Dynamic'
          publicIPAddress: { id: pip.id }
        }
      }
    ]
  }
}

// ------------------------------------------------------------------ VM

resource vm 'Microsoft.Compute/virtualMachines@2024-07-01' = {
  name: names.vm
  location: location
  identity: {
    // System-assigned: reads Key Vault and pulls images. User-assigned: one per workload (Entra tokens).
    type: 'SystemAssigned, UserAssigned'
    userAssignedIdentities: toObject(workloads, w => resourceId('Microsoft.ManagedIdentity/userAssignedIdentities', 'id-${prefix}-${toLower(w)}'), w => {})
  }
  properties: {
    hardwareProfile: { vmSize: vmSize }
    osProfile: {
      computerName: names.vm
      adminUsername: adminUser
      // Constant: Azure does not allow changing custom data later. deploy.sh installs the rest.
      customData: base64(loadTextContent('vm/cloud-init.yaml'))
      linuxConfiguration: {
        disablePasswordAuthentication: true
        ssh: { publicKeys: [{ path: '/home/${adminUser}/.ssh/authorized_keys', keyData: sshPublicKey }] }
      }
    }
    storageProfile: {
      imageReference: { publisher: 'Canonical', offer: 'ubuntu-24_04-lts', sku: 'server', version: 'latest' }
      osDisk: {
        createOption: 'FromImage'
        diskSizeGB: osDiskSizeGB
        managedDisk: { storageAccountType: 'StandardSSD_LRS' }
        deleteOption: 'Delete'
      }
    }
    networkProfile: { networkInterfaces: [{ id: nic.id, properties: { deleteOption: 'Delete' } }] }
    securityProfile: { securityType: 'TrustedLaunch', uefiSettings: { secureBootEnabled: true, vTpmEnabled: true } }
    diagnosticsProfile: { bootDiagnostics: { enabled: true } }
  }
  dependsOn: [identities]
}

// The VM reads secrets at deploy time and pulls images, retrying until these propagate.
resource kvVm 'Microsoft.Authorization/roleAssignments@2022-04-01' = {
  name: guid(kv.id, vm.id, roles.kvSecretsUser)
  scope: kv
  properties: {
    principalId: vm.identity.principalId
    principalType: 'ServicePrincipal'
    roleDefinitionId: subscriptionResourceId('Microsoft.Authorization/roleDefinitions', roles.kvSecretsUser)
  }
}

resource acrVm 'Microsoft.Authorization/roleAssignments@2022-04-01' = {
  name: guid(acr.id, vm.id, roles.acrPull)
  scope: acr
  properties: {
    principalId: vm.identity.principalId
    principalType: 'ServicePrincipal'
    roleDefinitionId: subscriptionResourceId('Microsoft.Authorization/roleDefinitions', roles.acrPull)
  }
}

// ------------------------------------------------------------------ outputs (no secrets)

output vmName string = vm.name
output acrName string = acr.name
output acrLoginServer string = acr.properties.loginServer
output keyVaultName string = kv.name
output tenantId string = subscription().tenantId
output appHost string = pip.properties.dnsSettings.fqdn
output speechRegion string = location
output identities array = [for (w, i) in workloads: {
  key: w
  clientId: identities[i].properties.clientId
  principalId: identities[i].properties.principalId
}]
